name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build:
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            OUT_FILE_NAME: autocut_macos.zip
            ASSET_MIME: application/zip
          - os: ubuntu-latest
            TARGET: linux
            OUT_FILE_NAME: autocut_linux.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            OUT_FILE_NAME: autocut_windows.zip
            ASSET_MIME: application/zip
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m virtualenv ./.venv
    - name: Build with pyinstaller for Windows
      if: runner.os == 'windows'
      run: |
        .venv\Scripts\activate
        pip install -r requirements.txt
        pyinstaller autocut.spec -y
    - name: Build with pyinstaller for Other-${{matrix.TARGET}}
      if: runner.os != 'windows'
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt
        pyinstaller autocut.spec -y
    - name: Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: ./dist
        dest: ./dist/autocut_${{matrix.TARGET}}.zip
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url
    - name: Get Release File Name & Upload URL
      id: get_release_info
      shell: bash
      run: |
        value=`cat release_url/release_url.txt`
        echo ::set-output name=upload_url::$value
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./dist/${{ matrix.OUT_FILE_NAME}}
        asset_name: ${{ matrix.OUT_FILE_NAME}}
        asset_content_type: ${{ matrix.ASSET_MIME}}
